<?php

return [
	'effects' => [
		'Simple' => [
			['id' => 0,  'name' => 'Static'],
			['id' => 1,  'name' => 'Blink'],
			['id' => 2,  'name' => 'Breath'],
			['id' => 8,  'name' => 'Random Color'],
			['id' => 9,  'name' => 'Single Dynamic'],
			['id' => 10, 'name' => 'Multi Dynamic'],
			['id' => 11, 'name' => 'Rainbow'],
			['id' => 19, 'name' => 'Twinkle'],
			['id' => 20, 'name' => 'Twinkle Random'],
			['id' => 21, 'name' => 'Twinkle Fade'],
			['id' => 22, 'name' => 'Twinkle Fade Random'],
			['id' => 23, 'name' => 'Sparkle'],
			['id' => 24, 'name' => 'Flash Sparkle'],
			['id' => 25, 'name' => 'Hyper Sparkle'],
			['id' => 26, 'name' => 'Strobe'],
			['id' => 27, 'name' => 'Strobe Rainbow'],
			['id' => 28, 'name' => 'Multi Strobe'],
			['id' => 29, 'name' => 'Blink Rainbow'],
			['id' => 45, 'name' => 'Fireworks'],
			['id' => 46, 'name' => 'Fireworks Random'],
			['id' => 48, 'name' => 'Fire Flicker'],
			['id' => 49, 'name' => 'Fire Flicker (soft)'],
			['id' => 50, 'name' => 'Fire Flicker (intense)'],
			['id' => 57, 'name' => 'Block Dissolve'],
			['id' => 63, 'name' => 'Rainbow Fireworks'],
			['id' => 64, 'name' => 'Trifade'],
		],
		'Wipe' => [
			['id' => 3,  'name' => 'Color Wipe'],
			['id' => 4,  'name' => 'Color Wipe Inverse'],
			['id' => 7,  'name' => 'Color Wipe Random'],
			['id' => 12, 'name' => 'Rainbow Cycle'],
			['id' => 16, 'name' => 'Theater Chase'],
			['id' => 17, 'name' => 'Theater Chase Rainbow'],
			['id' => 18, 'name' => 'Running Lights'],
			['id' => 30, 'name' => 'Chase White'],
			['id' => 31, 'name' => 'Chase Color'],
			['id' => 32, 'name' => 'Chase Random'],
			['id' => 33, 'name' => 'Chase Rainbow'],
			['id' => 34, 'name' => 'Chase Flash'],
			['id' => 35, 'name' => 'Chase Flash Random'],
			['id' => 36, 'name' => 'Chase Rainbow White'],
			['id' => 37, 'name' => 'Chase Blackout'],
			['id' => 38, 'name' => 'Chase Blackout Rainbow'],
			['id' => 40, 'name' => 'Running Color'],
			['id' => 41, 'name' => 'Running Red Blue'],
			['id' => 42, 'name' => 'Running Random'],
			['id' => 44, 'name' => 'Comet'],
			['id' => 47, 'name' => 'Merry Christmas'],
			['id' => 51, 'name' => 'Circus Combustus'],
			['id' => 52, 'name' => 'Halloween'],
			['id' => 53, 'name' => 'Bicolor Chase'],
			['id' => 54, 'name' => 'Tricolor Chase'],
			['id' => 60, 'name' => 'Running Random2'],
			['id' => 68, 'name' => 'Multi Comet'],
		],
		'Sweep' => [
			['id' => 5,  'name' => 'Color Wipe Reverse'],
			['id' => 6,  'name' => 'Color Wipe Reverse Inverse'],
			['id' => 13, 'name' => 'Scan'],
			['id' => 14, 'name' => 'Dual Scan'],
			['id' => 15, 'name' => 'Fade'],
			['id' => 39, 'name' => 'Color Sweep Random'],
			['id' => 43, 'name' => 'Larson Scanner'],
			['id' => 59, 'name' => 'Dual Larson'],
			['id' => 62, 'name' => 'Rainbow Larson'],
		],
		'Special' => [
			['id' => 55, 'name' => 'TwinkleFOX'],
			['id' => 56, 'name' => 'Rain'],
			['id' => 58, 'name' => 'ICU'],
			['id' => 61, 'name' => 'Filler Up'],
			['id' => 65, 'name' => 'VU Meter'],
			['id' => 66, 'name' => 'Heartbeat'],
			['id' => 67, 'name' => 'Bits'],
			['id' => 69, 'name' => 'Flipbook'],
			['id' => 70, 'name' => 'Popcorn'],
			['id' => 71, 'name' => 'Oscillator'],
		],
	],
];
